version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - ./nginx/dev.env
    restart: always
    ports:
      - 80:80
    depends_on:
      - app