version: '3'
services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/data/public-viewer-book-rec-app-2-15084ef3a6b9.json:/app/data/public-viewer-book-rec-app-2-15084ef3a6b9.json
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - ./nginx/dev.env
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask-app