apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-rec-app
  name: book-rec-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-flask-app
  template:
    metadata:
      labels:
        app: multi-container-flask-app
    spec:
      containers:
      - image: alexnimjli/book_rec_flask_app:1.2.0
        name: flask-app
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: app/data/public-viewer-book-rec-app-2-15084ef3a6b9.json
          name: gbq-public-key
          subPath: public-key.json
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 1000
        resources:
          requests:
            memory: "700Mi"
            cpu: "0.5"
          limits:
            memory: "750Mi"
            cpu: "1"
      - image: nginx:1.13-alpine
        name: nginx-proxy
        command: ["/bin/sh", "-c", "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf; nginx -g 'daemon off;'"]
        ports:
        - containerPort: 8888
        env:
          - name: SERVER_NAME
            valueFrom:
              configMapKeyRef:
                name: nginx-config
                key: SERVER_NAME
          - name: FLASK_APP_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: nginx-config
                key: FLASK_APP_SERVICE_HOST
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf.template
          name: nginx-config
          subPath: nginx.conf
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.15"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: gbq-public-key
        secret:
          secretName: gbq-public-key
          optional: False
