# ClusterIP serivce to access flask app
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask_app
  name: flask_app_clusterip
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: flask_app
  type: ClusterIP
---
# NodePort service to expose app via nginx
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx_nodeport
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort