# NodePort service to expose app via nginx
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-nodeport
spec:
  ports:
  - protocol: TCP
    port: 38888
    targetPort: 8888
  selector:
    app: flask-app
  type: NodePort